FROM alpine
ENV VERSION 6.7.1
ENV BASE_URL https://artifacts.elastic.co/downloads/logstash
ENV TARBALL "${BASE_URL}/logstash-${VERSION}.tar.gz"

RUN apk add --no-cache openjdk8-jre bash

RUN set -ex && \
    cd /tmp && wget -O logstash.tar.gz "$TARBALL" && \
    tar -xzf logstash.tar.gz && \
    mv logstash-$VERSION /usr/share/logstash && \
    rm -rf /tmp/*

ENV PATH /usr/share/logstash/bin:/sbin:$PATH
ENV LS_SETTINGS_DIR /usr/share/logstash/config
ENV LANG='en_US.UTF-8' LC_ALL='en_US.UTF-8'
